In [ ]:
from google.colab import files
uploaded = files.upload()

Saving HeartDisease.csv to HeartDisease.csv

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('HeartDisease.csv')

In [ ]:
df

     age  sex  cp  trestbps  chol  fbs  restecg  target
0     63    1   3       145   233    1        0       1
1     37    1   2       130   250    0        1       1
2     41    0   1       130   204    0        0       1
3     56    1   1       120   236    0        1       1
4     57    0   0       120   354    0        1       1
..   ...  ...  ..       ...   ...  ...      ...     ...
298   57    0   0       140   241    0        1       0
299   45    1   3       110   264    0        1       0
300   68    1   0       144   193    1        1       0
301   57    1   0       130   131    0        1       0
302   57    0   1       130   236    0        0       0

[303 rows x 8 columns]

In [ ]:
df['Gender'] = df.sex.replace({1: 'Male', 0: 'Female'})
p = df.groupby('Gender')['target'].agg([lambda z: np.sum(z==1),'size'])
p.columns = ['HeartDisease', 'Total']

p

        HeartDisease  Total
Gender
Female            72     96
Male              93    207

In [ ]:
from statsmodels.stats.proportion import proportions_ztest
import numpy as np

In [ ]:
significance = 0.01
successes = np.array([ p.HeartDisease.Female, p.HeartDisease.Male])
samples = np.array([p.Total.Female, p.Total.Male])

In [ ]:
stat, p_value = proportions_ztest(count=successes, nobs=samples, alternative='two-sided')

In [ ]:
print('z_stat: %0.5f, p_value: %0.6f' % (stat, p_value))
if p_value < significance:
  print ("Reject the null hypothesis")
else:
  print ("Accept the null hypothesis")

z_stat: 4.89023, p_value: 0.000001
Reject the null hypothesis

In [ ]:
df['target'].replace({1:'Yes', 0:'No'},inplace=True)

In [ ]:
df

     age  sex  cp  trestbps  chol  fbs  restecg target  Gender
0     63    1   3       145   233    1        0    Yes    Male
1     37    1   2       130   250    0        1    Yes    Male
2     41    0   1       130   204    0        0    Yes  Female
3     56    1   1       120   236    0        1    Yes    Male
4     57    0   0       120   354    0        1    Yes  Female
..   ...  ...  ..       ...   ...  ...      ...    ...     ...
298   57    0   0       140   241    0        1     No  Female
299   45    1   3       110   264    0        1     No    Male
300   68    1   0       144   193    1        1     No    Male
301   57    1   0       130   131    0        1     No    Male
302   57    0   1       130   236    0        0     No  Female

[303 rows x 9 columns]

In [ ]:
Table1 = pd.crosstab(df.Gender, df.target, margins=True)

In [ ]:
Table1

target   No  Yes  All
Gender
Female   24   72   96
Male    114   93  207
All     138  165  303

In [ ]:
Table1 = pd.crosstab(df.Gender, df.target)

In [ ]:
Table1

target   No  Yes
Gender
Female   24   72
Male    114   93

In [ ]:
from scipy.stats import chi2_contingency
chi2, p, dof, expected = chi2_contingency(Table1,correction=False)
print(f"chi2 statistic: {chi2:.5g}")
print(f"p-value: {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)
significance = 0.01
if p < significance:
  print ("sex and have heart disease are dependent")
else:
  print ("sex and have heart disease are independent")

chi2 statistic: 23.914
p-value: 1.0072e-06
degrees of freedom: 1
expected frequencies:
[[ 43.72277228  52.27722772]
 [ 94.27722772 112.72277228]]
sex and have heart disease are dependent